
  [[main]]
  name = "Publications" 
  identifier = "publications"
  weight = 100
  url = "/publications/"
 
  [[main]]
  name = "Research Highlights" 
  identifier = "research_highlights"
  weight = 200
  url = "/research_highlights/"
 
  [[main]]
  name = "Cover Art" 
  identifier = "cover_art"
  weight = 300
  url = "/cover_art/"
 
  [[main]]
  name = "CV" 
  identifier = "cv"
  weight = 400
  url = "/cv/"
 
  [[main]]
  name = "Software" 
  identifier = "software"
  weight = 500
  url = "/software/"
 
  [[main]]
  name = "Supervision" 
  identifier = "supervision"
  weight = 600
  url = "/supervision/"


