title: Benjamin A. D. Williamson 
description: PDRA in Computational Materials Design
email: benjamin.williamson@ntnu.no
twitter_username: bad_williamson
sass:
        sass_dir: _sass
include: ['_pages']
kramdown:
 input: GFM

google_analytics: UA-125437750-1
