title: Benjamin A. D. Williamson 
description: Researcher in Materials Simulations
email: benjamin.williamson@ntnu.no
twitter_username: bad_williamson
sass:
        sass_dir: _sass
include: ['_pages']
kramdown:
 input: GFM

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
